name: fontawesome
description: An absolute bare-bones web app.
version: 1.0.1
homepage: https://github.com/tejainece/fontawesome
author: Ravi Teja Gudapati <tejainece@gmail.com>

environment:
  sdk: '>=2.0.0-dev.55.0 <2.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  build_runner: ^0.8.7
  build_web_compilers: ^0.4.0
